#!/bin/sh

set -e

ENABLE_GITLEAKS=$(git config --get hooks.gitleaks-enable)

if [ "$ENABLE_GITLEAKS" != "true" ]; then
  echo "Gitleaks pre-commit hook is disabled. Skipping check."
  exit 0
fi

install_gitleaks() {
  echo "Installing gitleaks..."

  OS=$(uname)
  if [ "$OS" = "Linux" ]; then
    if ! command -v wget &> /dev/null; then
      echo "wget could not be found. Please install wget and try again."
      exit 1
    fi
    wget -qO- https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz | tar xvz -C /tmp
    mv /tmp/gitleaks /usr/local/bin/
  elif [ "$OS" = "Darwin" ]; then
    if ! command -v brew &> /dev/null; then
      echo "Homebrew is not installed. Please install Homebrew and try again."
      exit 1
    fi
    brew install gitleaks
  else
    echo "Unsupported OS: $OS"
    exit 1
  fi
}

if ! command -v gitleaks &> /dev/null; then
  install_gitleaks
fi

gitleaks detect --source . --exit-code 1

if [ $? -ne 0 ]; then
  echo "Gitleaks detected secrets in your code. Commit rejected."
  exit 1
fi

echo "No secrets detected by Gitleaks. Proceeding with commit."
exit 0