name: Workflow demo

on: 
  push:
    branches:
    - '**'

jobs:
  echo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Configure Git author
        run: |
          git config --global user.email "zakharchuk.vadym@gmail.com"
          git config --global user.name "Vadym"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Update tag in values.yaml
        run: |
          sed -i 's/^  tag: .*/  tag: "${{ github.sha }}"/' demo/values.yaml
          git add demo/values.yaml
          git commit -m "Update tag to ${{ github.sha }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          IMAGE=vzak/node-hello-world:${{ github.sha }}
          docker build -t ${IMAGE} .
          docker push ${IMAGE}
          if [ $? -eq 0 ]; then
            echo "Image successfully pushed to Docker Hub."
          else
            echo "Failed to push the image to Docker Hub."
            exit 1
          fi