name: Gitleaks Check

on:
  workflow_call:

jobs:
  gitleaks-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Get latest Gitleaks release URL
      id: get_release
      run: |
            curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
            | grep "browser_download_url.*linux-amd64" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
  
    - name: Install Gitleaks
      run: |
        tar -xzf gitleaks-linux-amd64.tar.gz -C /tmp
        sudo mv /tmp/gitleaks /usr/local/bin/
        rm gitleaks-linux-amd64.tar.gz

    - name: Run Gitleaks
      run: |
        gitleaks detect --source . --exit-code 1
